# Generated by Django 5.2.4 on 2025-07-07 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=20)),
                ('fuel_type', models.CharField(choices=[('gas', 'Gas'), ('diesel', 'Diesel'), ('hybrid', 'Hybrid'), ('electric', 'Electric')], max_length=20)),
                ('transmission', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], max_length=20)),
                ('exterior_color', models.CharField(max_length=30)),
                ('interior_color', models.CharField(max_length=30)),
                ('vin', models.CharField(max_length=17, unique=True)),
                ('description', models.TextField(blank=True)),
                ('features', models.TextField(blank=True, help_text='List special features, one per line')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='car_images/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='car_images/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='car_images/')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='car_images/')),
                ('image_5', models.ImageField(blank=True, null=True, upload_to='car_images/')),
                ('is_available', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
                'ordering': ['-created_at'],
            },
        ),
    ]
